# inspired by https://github.com/docker/build-push-action/blob/a63b18d/docs/advanced/cache.md#github-cache

name: Docker Image CI
on:
  push:
    branches: [main, setup/ci]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        ghc: ["8.8.4"]
        resolver: ["lts-16.12"]
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: login to GH container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: ./.devcontainer/
        push: false
        tags: user/app:latest
        build-args: |
          GHC_VERSION=${{ matrix.ghc }}
          STACK_RESOLVER=${{ matrix.resolver }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    # - name: Build the Docker image
    #   run: >
    #       DOCKER_BUILDKIT=1 docker build ./.devcontainer/
    #       --file ./.devcontainer/Dockerfile
    #       --build-arg GHC_VERSION=${{ matrix.ghc }}
    #       --build-arg STACK_RESOLVER=${{ matrix.resolver }}
    #       --compress
    #       --tag vlza/haskelldevenv:${{ matrix.ghc }}-${{ matrix.resolver }}-$(date +%s)

# TODO: Trigger release on tag, publish containers.
